[package]
name = "Server"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
rand = "0.8.5"
dashmap = "6.1.0"
zeroize = "1.8.1"
fips203 = {version = "0.4.1", features=["ml-kem-1024", "default-rng"]}
fips204 = {version = "0.4.5", features=["ml-dsa-87", "default-rng"]}